### ISSUE TITLE
مشکل در نمایش دستکتاپ

### ISSUE THREAD

**Issue by asbsiah** [MatinDehghanian/Ourenus#1]
سلام متین خسته نباشی ممنون بابت تمپلیت جذابت 
لطفا این مورد رو تنظیم کن که عکس میزارم 

![ssss](https://github.com/user-attachments/assets/2a4314c1-dab1-4181-88f6-b05eed7e9367)

**Comment by asbsiah** [comment]
و همچنین این مشکل در نمودار زمان 

![eee](https://github.com/user-attachments/assets/17de1be9-1cc9-48b0-8a72-e3551b2cb3f4)

**Comment by MatinDehghanian** [comment]
> سلام متین خسته نباشی ممنون بابت تمپلیت جذابت لطفا این مورد رو تنظیم کن که عکس میزارم
> 
> ![ssss](https://private-user-images.githubusercontent.com/171607465/390000128-2a4314c1-dab1-4181-88f6-b05eed7e9367.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2NDUxMDcsIm5iZiI6MTczMjY0NDgwNywicGF0aCI6Ii8xNzE2MDc0NjUvMzkwMDAwMTI4LTJhNDMxNGMxLWRhYjEtNDE4MS04OGY2LWIwNWVlZDdlOTM2Ny5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNlQxODEzMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZGI4ZmQyZWMzZGM4M2E3Zjk3ZDJmYjQwMzJkMjcyYmRkZjc2YTQxZGUyYWRmOTRjZjk4YmM4ODZmZjQyMGIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.8AglANbw6YlBept6d9cggn9Lsk0zhycgO-0nKInUtX4)

Solved ✅

**Comment by asbsiah** [comment]
> > سلام متین خسته نباشی ممنون بابت تمپلیت جذابت لطفا این مورد رو تنظیم کن که عکس میزارم
> > ![ssss](https://private-user-images.githubusercontent.com/171607465/390000128-2a4314c1-dab1-4181-88f6-b05eed7e9367.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2NDUxMDcsIm5iZiI6MTczMjY0NDgwNywicGF0aCI6Ii8xNzE2MDc0NjUvMzkwMDAwMTI4LTJhNDMxNGMxLWRhYjEtNDE4MS04OGY2LWIwNWVlZDdlOTM2Ny5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNlQxODEzMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZGI4ZmQyZWMzZGM4M2E3Zjk3ZDJmYjQwMzJkMjcyYmRkZjc2YTQxZGUyYWRmOTRjZjk4YmM4ODZmZjQyMGIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.8AglANbw6YlBept6d9cggn9Lsk0zhycgO-0nKInUtX4)
> 
> Solved ✅

Thanks babe

**Comment by asbsiah** [comment]
> > سلام متین خسته نباشی ممنون بابت تمپلیت جذابت لطفا این مورد رو تنظیم کن که عکس میزارم
> > ![ssss](https://private-user-images.githubusercontent.com/171607465/390000128-2a4314c1-dab1-4181-88f6-b05eed7e9367.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2NDUxMDcsIm5iZiI6MTczMjY0NDgwNywicGF0aCI6Ii8xNzE2MDc0NjUvMzkwMDAwMTI4LTJhNDMxNGMxLWRhYjEtNDE4MS04OGY2LWIwNWVlZDdlOTM2Ny5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNlQxODEzMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZGI4ZmQyZWMzZGM4M2E3Zjk3ZDJmYjQwMzJkMjcyYmRkZjc2YTQxZGUyYWRmOTRjZjk4YmM4ODZmZjQyMGIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.8AglANbw6YlBept6d9cggn9Lsk0zhycgO-0nKInUtX4)
> 
> Solved ✅

عزیز این قسمت نمودار زمان هنوز 0 هستش و تغییرات رو نمیگیره مثل ترافیک 


![ssssss](https://github.com/user-attachments/assets/bfa2841e-bcd3-4e0a-8199-2ff7749353a8)

**Comment by MatinDehghanian** [comment]
solved
