### ISSUE TITLE
نصب روی هاست

### ISSUE THREAD

**Issue by reza4fprm** [MatinDehghanian/Ourenus#3]
ممنونم میشم مسیر و اموزش راه اندازی روی هاست رو هم بفرمایید . 
دامنه ساب رو تغییر دادم از مرزبان و روی هاست آوردم بالا

**Comment by Non-believer** [comment]
اره مشکل منم هست نمی‌دونم چطوری باید روی هاست رانش کنم 
تو هستم یه پوشه sub ساختم ی فایل htaccess هم ریختم توش و php که برای این تمپلیت بود هم کنارش گذاشتم 
ولی خب متاسفانه کار نکرد و چیزی بالا نیومد دقیقا نمی‌دونم مشکل از کجای کاره
